export const SET_LOADING = 'SET_LOADING'


//user
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'


// product
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'FETCH_JOBS_ERROR'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_JOB_ERROR'
export const DELETE_PRODUCT_ERROR = 'DELETE_JOB_ERROR'
export const FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_SINGLE_JOB_SUCCESS'
export const FETCH_SINGLE_PRODUCT_ERROR = 'FETCH_SINGLE_JOB_ERROR'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_JOB_ERROR'

// ALERT
export const SET_ALERT = 'SET_ALERT'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'



